ALTER TABLE tickets ADD COLUMN IF NOT EXISTS due_at timestamptz;

ALTER TYPE ticket_audit_type ADD VALUE IF NOT EXISTS 'ATTACHMENT_ADDED';
ALTER TYPE ticket_audit_type ADD VALUE IF NOT EXISTS 'ATTACHMENT_REMOVED';
